# Generated by Django 6.1.1 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('barber', 'Barber'), ('stylist', 'Stylist'), ('Barber_Stylist', 'Barber & Stylist')], max_length=35),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], max_length=35),
        ),
    ]
