# Generated by Django 6.1.1 on 2026-09-29 14:27

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='full_name only support letters and space.', regex='^[A-Za-z]+(?: [A-Za-z]+)*$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('booking_date', models.DateField()),
                ('session_start_date_time', models.DateTimeField()),
                ('session_end_date_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=20)),
                ('reason_for_cancellation', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_source', models.CharField(choices=[('ONLINE', 'Online'), ('WALK_IN', 'Walk In')], default='ONLINE', max_length=20)),
                ('booked_by', models.CharField(max_length=15)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.staffprofile')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.color')),
                ('hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.hairstyle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
            ],
            options={
                'indexes': [models.Index(fields=['barber', 'booking_date', 'session_start_date_time'], name='bookings_bo_barber__2008c9_idx'), models.Index(fields=['booking_date', 'status'], name='bookings_bo_booking_b730a0_idx'), models.Index(fields=['booking_date', 'barber', 'status'], name='bookings_bo_booking_0ed96d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('session_start_date_time__lt', models.F('session_end_date_time'))), name='booking_session_start_time_should_before_session_end_time')],
            },
        ),
    ]
