# Generated by Django 6.0.6 on 2026-08-28 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='full_name only support letters and space.', regex='^[A-Za-z]+(?: [A-Za-z]+)*$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 11 digits.', regex='^(020|021|070|080|081|090|091)\\d{8}$')])),
                ('booking_date', models.DateField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=20)),
                ('reason_for_cancellation', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_source', models.CharField(choices=[('ONLINE', 'Online'), ('WALK_IN', 'Walk In')], default='ONLINE', max_length=20)),
                ('booked_by', models.CharField(max_length=15)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.staffprofile')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.color')),
                ('hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.hairstyle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
            ],
        ),
    ]
