# Generated by Django 6.1.1 on 2026-10-01 13:41

import backend.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=backend.bookings.models.generate_booking_reference, max_length=30, unique=True),
        ),
    ]
