# Generated by Django 6.1.1 on 2026-09-10 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
        ('bookings', '0003_booking_bookings_bo_barber__0e0f38_idx_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='event_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_date__gte', datetime.date(2026, 9, 10))), name='event_booking_date_today_or_later'),
        ),
    ]
