# Generated by Django 6.1.1 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_department_and_more'),
        ('bookings', '0004_booking_event_start_before_end_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='event_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='event_booking_date_today_or_later',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='booking_start_time_should_before_end'),
        ),
    ]
