# Generated by Django 6.1.1 on 2026-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_event_start_before_end_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_8a7545_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
