# Generated by Django 6.1.1 on 2026-09-16 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_department_and_more'),
        ('bookings', '0006_remove_booking_bookings_bo_booking_8a7545_idx_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_start_time_should_before_end',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_barber__0e0f38_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='session_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 16, 16, 43, 55, 325070, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='session_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 16, 16, 44, 20, 898924, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['barber', 'booking_date', 'session_start_date_time'], name='bookings_bo_barber__2008c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('session_start_date_time__lt', models.F('session_end_date_time'))), name='booking_session_start_time_should_before_session_end_time'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
