# Generated by Django 6.0.6 on 2026-08-28 16:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonBookingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_duration_buffer', models.PositiveIntegerField()),
                ('allow_online_booking', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SalonBookingSetting',
                'verbose_name_plural': 'SalonBookingSetting',
            },
        ),
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=255)),
                ('salon_address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('salon_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('salon_currency', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'SalonInfo',
                'verbose_name_plural': 'SalonInfo',
            },
        ),
    ]
