# Generated by Django 6.1.1 on 2026-09-29 14:27

import backend.salon_settings.validators
import phonenumber_field.modelfields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonBookingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_slot_interval', models.PositiveIntegerField()),
                ('allow_online_booking', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SalonBookingSetting',
                'verbose_name_plural': 'SalonBookingSetting',
            },
        ),
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon_name', models.CharField(max_length=255)),
                ('salon_address', models.CharField(max_length=255)),
                ('salon_email', models.EmailField(default='info@salon.com', max_length=255)),
                ('salon_time_zone', timezone_field.fields.TimeZoneField(default='Europe/London')),
                ('salon_country', models.CharField(default='GB', max_length=2, validators=[backend.salon_settings.validators.validate_country_code])),
                ('salon_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('salon_currency', models.CharField(default='GBP', max_length=3, validators=[backend.salon_settings.validators.validate_currency_code])),
                ('salon_open_time', models.TimeField(default='09:00')),
                ('salon_close_time', models.TimeField(default='21:30')),
            ],
            options={
                'verbose_name': 'SalonInfo',
                'verbose_name_plural': 'SalonInfo',
                'constraints': [models.CheckConstraint(condition=models.Q(('salon_open_time__lt', models.F('salon_close_time'))), name='salon_open_before_close')],
            },
        ),
    ]
