# Generated by Django 6.0.6 on 2026-09-03 16:35

import backend.salon_settings.validators
import django.utils.timezone
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonbookingsetting',
            old_name='booking_duration_buffer',
            new_name='booking_slot_interval',
        ),
        migrations.RemoveField(
            model_name='saloninfo',
            name='country',
        ),
        migrations.AddField(
            model_name='salonbookingsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salonbookingsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='salon_close_time',
            field=models.TimeField(default='21:30'),
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='salon_country',
            field=models.CharField(default='England', max_length=2, validators=[backend.salon_settings.validators.validate_country_code]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='salon_email',
            field=models.EmailField(default='info@salon.com', max_length=255),
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='salon_open_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='salon_time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saloninfo',
            name='salon_currency',
            field=models.CharField(default='GBP', max_length=3, validators=[backend.salon_settings.validators.validate_currency_code]),
        ),
        migrations.AddConstraint(
            model_name='saloninfo',
            constraint=models.CheckConstraint(condition=models.Q(('salon_open_time__lt', models.F('salon_close_time'))), name='salon_open_before_close'),
        ),
    ]
