# Generated by Django 6.1.1 on 2026-09-08 17:58

import backend.salon_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_settings', '0002_rename_booking_duration_buffer_salonbookingsetting_booking_slot_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloninfo',
            name='salon_country',
            field=models.CharField(default='England', max_length=2, validators=[backend.salon_settings.validators.validate_country_code]),
        ),
    ]
