# Generated by Django 6.1.1 on 2026-09-28 09:21

import backend.salon_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_settings', '0003_alter_saloninfo_salon_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloninfo',
            name='salon_country',
            field=models.CharField(default='GB', max_length=2, validators=[backend.salon_settings.validators.validate_country_code]),
        ),
    ]
