# Generated by Django 6.1.1 on 2026-09-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTimeAndOffDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_date', models.DateField()),
                ('break_start_date_time', models.DateTimeField()),
                ('break_end_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('break', 'Break'), ('off_day', 'Off Day'), ('on_leave', 'On Leave'), ('sick_leave', 'Sick Leave'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaktime_or_off_days', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'BreakTimeAndOffDays',
                'verbose_name_plural': 'BreakTimeAndOffDays',
                'ordering': ['-break_date', 'break_start_date_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('break_start_date_time__lt', models.F('break_end_date_time'))), name='break_start_time_should_before_end')],
            },
        ),
    ]
