# Generated by Django 6.0.6 on 2026-08-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTimeAndOffDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('break', 'Break'), ('off_day', 'Off Day'), ('on_leave', 'On Leave'), ('sick_leave', 'Sick Leave'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaktime_or_off_days', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'BreakTimeAndOffDays',
                'verbose_name_plural': 'BreakTimeAndOffDays',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
