# Generated by Django 6.1.1 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_department_and_more'),
        ('breakperiods', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='breaktimeandoffdays',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='break_start_time_should_before_end'),
        ),
    ]
