# Generated by Django 6.1.1 on 2026-09-17 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_department_and_more'),
        ('breakperiods', '0002_breaktimeandoffdays_break_start_time_should_before_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaktimeandoffdays',
            options={'ordering': ['-break_date', 'break_start_date_time'], 'verbose_name': 'BreakTimeAndOffDays', 'verbose_name_plural': 'BreakTimeAndOffDays'},
        ),
        migrations.RemoveConstraint(
            model_name='breaktimeandoffdays',
            name='break_start_time_should_before_end',
        ),
        migrations.RenameField(
            model_name='breaktimeandoffdays',
            old_name='date',
            new_name='break_date',
        ),
        migrations.AddField(
            model_name='breaktimeandoffdays',
            name='break_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 17, 18, 1, 37, 129284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaktimeandoffdays',
            name='break_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 17, 18, 1, 49, 525061, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='breaktimeandoffdays',
            constraint=models.CheckConstraint(condition=models.Q(('break_start_date_time__lt', models.F('break_end_date_time'))), name='break_start_time_should_before_end'),
        ),
        migrations.RemoveField(
            model_name='breaktimeandoffdays',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='breaktimeandoffdays',
            name='start_time',
        ),
    ]
