# Generated by Django 6.1.1 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakperiods', '0003_alter_breaktimeandoffdays_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktimeandoffdays',
            name='break_date',
            field=models.DateTimeField(),
        ),
    ]
