# Generated by Django 6.1.1 on 2026-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakperiods', '0004_alter_breaktimeandoffdays_break_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktimeandoffdays',
            name='break_date',
            field=models.DateField(),
        ),
    ]
