# Generated by Django 6.1.1 on 2026-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakperiods', '0005_alter_breaktimeandoffdays_break_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktimeandoffdays',
            name='status',
            field=models.CharField(choices=[('break', 'Break'), ('off_day', 'Off Day'), ('on_leave', 'On Leave'), ('sick_leave', 'Sick Leave'), ('personal', 'Personal'), ('other', 'Other')], max_length=20),
        ),
    ]
