"""
Django settings for core_config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENV = os.getenv("DJANGO_ENV", "dev")

if ENV == "prod":
    load_dotenv(BASE_DIR / ".env-prod")

    # SECRET_KEY = os.getenv("SECRET_KEY_PROD")
    #
    # if not SECRET_KEY:
    #     raise ValueError("SECRET_KEY_PROD not found")

else:
    load_dotenv(BASE_DIR / ".env-dev")

    # SECRET_KEY = os.getenv("SECRET_KEY_DEV")
    #
    # if not SECRET_KEY:
    #     raise ValueError("SECRET_KEY_DEV not found")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


LOGIN_URL = "staff_dashboard_login"



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",

    'backend.accounts',
    'backend.bookings',
    'backend.breakperiods',
    'backend.inventory',
    'backend.services',
    'backend.salon_settings',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_config.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [ BASE_DIR / "frontend/static",]

# STATICFILES_STORAGE = ( "whitenoise.storage.CompressedManifestStaticFilesStorage" )

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Django session to expire after 1 hour
# SESSION_COOKIE_AGE = 60 * 60 * 1

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        "backend.session_and_jwt_auth.session_and_jwt_auth.CookieJWTAuthentication",
    ),

    "EXCEPTION_HANDLER": "backend.exceptions.custom_exception_handler.custom_exception_handler",
}

AUTH_USER_MODEL = "accounts.User"





